### ISSUE TITLE
docker-compose up xsshunterexpress throws error in windows 10

### ISSUE THREAD

**Issue by tharinda2012** [mandatoryprogrammer/xsshunter-express#2]
I run this command "docker-compose up xsshunterexpress" and following error results :

xsshunterexpress_1  | Starting server...
xsshunterexpress_1  | (node:28) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
xsshunterexpress_1  | (node:28) UnhandledPromiseRejectionWarning: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND postgresdb
xsshunterexpress_1  |     at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:175:24)
xsshunterexpress_1  |     at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
xsshunterexpress_1  |     at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:315:19)
xsshunterexpress_1  |     at Connection.emit (events.js:314:20)
xsshunterexpress_1  |     at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:53:12)
xsshunterexpress_1  |     at Socket.emit (events.js:314:20)
xsshunterexpress_1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
xsshunterexpress_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
xsshunterexpress_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
xsshunterexpress_1  | (node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
xsshunterexpress_1  | (node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
xsshunter-express_xsshunterexpress_1 exited with code 0

What could be the reason for this?

Docker desktop: Version 2.0.0.3 (31259)
docker-compose.yaml is set to 3.3 (3.9 not compatible with this docker version)
node version: v12.18.2

**Comment by omniaprobate** [comment]
Seeing a similar issue on my Ubuntu AWS instance, at least in terms of the DeprecationWarning:

ubuntu@ip-xxx-xx-x-xxx:~/xsshunter-express$ sudo docker-compose up xsshunterexpress
xsshunter-express_postgresdb_1 is up-to-date
xsshunter-express_xsshunterexpress_1 is up-to-date
Attaching to xsshunter-express_xsshunterexpress_1
xsshunterexpress_1  | Initializing SSL/TLS...
xsshunterexpress_1  | [default] store.module: greenlock-store-fs
xsshunterexpress_1  | [default] challenges.http-01.module: acme-http-01-standalone
xsshunterexpress_1  | [default] renewOffset: -45d
xsshunterexpress_1  | [default] renewStagger: 3d
xsshunterexpress_1  | [default] accountKeyType: EC-P256
xsshunterexpress_1  | [default] serverKeyType: RSA-2048
xsshunterexpress_1  | 
xsshunterexpress_1  | [default] subscriberEmail: <email_from_yaml_file>
xsshunterexpress_1  | [default] agreeToTerms: (show notice on use)
xsshunterexpress_1  | 
xsshunterexpress_1  | [skip] 'server.js' exists
xsshunterexpress_1  | [skip] 'app.js' exists
xsshunterexpress_1  | 
xsshunterexpress_1  | subject: "<hostname_from_yamlfile>"
xsshunterexpress_1  | altnames: ["<hostname_from_yamlfile>"]
xsshunterexpress_1  | renewAt: 1
xsshunterexpress_1  | defaults:
xsshunterexpress_1  | 	store:{"module":"greenlock-store-fs"}
xsshunterexpress_1  | 	challenges:{"http-01":{"module":"acme-http-01-standalone"}}
xsshunterexpress_1  | Starting server...
**xsshunterexpress_1  | (node:29) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log**
xsshunterexpress_1  | Executed (default): CREATE TABLE IF NOT EXISTS "collected_pages" ("id" UUID NOT NULL DEFAULT 'c61e987b-f4e2-44fd-8fc0-5a44ff945afb' , "uri" TEXT NOT NULL, "html" TEXT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id")); Elapsed time: 47ms
xsshunterexpress_1
...
...
<many more lines of SQL statements> 
<Attention> Admin password section <Attention>
<many more lines of SQL statements> 
<Initializing SSL/TLS...>
xsshunterexpress_1  | (node:29) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
<several more repeats of SQL statements, "Initializing SSL/TLS...">

**Comment by xElkomy** [comment]
Do you solve it?

**Comment by DGUTdgut** [comment]
I got below error

[root@iZt4ndkfpmx5eozp4q0aowZ xsshunter-express]# docker-compose up xsshunterexpress
Building xsshunterexpress
Sending build context to Docker daemon  66.14MB

Step 1/25 : FROM node:12
 ---> 6c8de432fc7f
Step 2/25 : RUN mkdir /app/
 ---> Using cache
 ---> 4abafa969f34
Step 3/25 : WORKDIR /app/
 ---> Using cache
 ---> 4794f390a553
Step 4/25 : COPY front-end/ /app/front-end/
 ---> Using cache
 ---> 73c41d33c9ff
Step 5/25 : WORKDIR /app/front-end/
 ---> Using cache
 ---> 02f480253d47
Step 6/25 : RUN npm install
 ---> Running in 71e72397d17f
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/vue-loader failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-11T14_33_26_267Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1
