### ISSUE TITLE
docker-compose fails on step 25

### ISSUE THREAD

**Issue by mikedesu** [mandatoryprogrammer/xsshunter-express#30]
See error message below. 
`uname -a` yields `Linux xsshunter 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`

```
xsshunterexpress_1  | renewAt: 1
xsshunterexpress_1  | defaults:
xsshunterexpress_1  |   store:{"module":"greenlock-store-fs"}
xsshunterexpress_1  |   challenges:{"http-01":{"module":"acme-http-01-standalone"}}
xsshunterexpress_1  | Starting server...
xsshunterexpress_1  | (node:29) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
xsshunterexpress_1  | (node:29) UnhandledPromiseRejectionWarning: SequelizeConnectionError: could not open file "global/pg_filenode.map": Permission denied
xsshunterexpress_1  |     at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
xsshunterexpress_1  |     at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
xsshunterexpress_1  |     at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:325:19)
xsshunterexpress_1  |     at Connection.emit (events.js:314:20)
xsshunterexpress_1  |     at /app/node_modules/pg/lib/connection.js:115:12
xsshunterexpress_1  |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
xsshunterexpress_1  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)
xsshunterexpress_1  |     at Socket.emit (events.js:314:20)
xsshunterexpress_1  |     at addChunk (_stream_readable.js:297:12)
xsshunterexpress_1  |     at readableAddChunk (_stream_readable.js:272:9)
xsshunterexpress_1  | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
xsshunterexpress_1  | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
xsshunter-express_xsshunterexpress_1 exited with code 0
```

**Comment by Rffrench** [comment]
i got the same error, could you fix this?

**Comment by VestaCord** [comment]
Have the same issue, logs show it has to do with Postgresdb failing with permissions.

```
docker-compose logs postgresdb
WARN[0000] /home/kali/bin/xsshunter-express/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
postgresdb-1  | mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied
postgresdb-1  | mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied
postgresdb-1  | mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied
postgresdb-1  | mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied
```

**Comment by VestaCord** [comment]
This is the directory where there is an error in permissions.

```
 tail -n2 docker-compose.yml
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data/pgdata
```
The folder in question has its permissions set after the compose file is ran, perhaps set by the `postgresdb` container, therefore it is impossible to manually override these restrictive permissions.

```
drwx------ 2 dnsmasq root  4096 Oct 14 06:45 postgres-db-data
```
