### ISSUE TITLE
ERROR: When I use a payload, my XSSHunter stops

### ISSUE THREAD

**Issue by trustinveritas** [mandatoryprogrammer/xsshunter-express#35]
```text
xsshunterexpress_1  | (node:29) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
xsshunterexpress_1  |     at /app/app.js:184:46
xsshunterexpress_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
xsshunterexpress_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
xsshunterexpress_1  |     at /app/node_modules/express-jsonschema/index.js:191:13
xsshunterexpress_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
xsshunterexpress_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
xsshunterexpress_1  |     at Immediate.<anonymous> (/app/node_modules/multer/lib/make-middleware.js:53:37)
xsshunterexpress_1  |     at processImmediate (internal/timers.js:463:21)
xsshunterexpress_1  | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
xsshunterexpress_1  | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
xsshunterexpress_1  | Executed (default): SELECT "id", "key", "value", "createdAt", "updatedAt" FROM "settings" AS "settings" WHERE "settings"."key" = 'PAGES_TO_COLLECT'; Elapsed time: 1ms
xsshunterexpress_1  | Executed (default): SELECT "id", "key", "value", "createdAt", "updatedAt" FROM "settings" AS "settings" WHERE "settings"."key" = 'CHAINLOAD_URI'; Elapsed time: 0ms
xsshunterexpress_1  | events.js:291
xsshunterexpress_1  |       throw er; // Unhandled 'error' event
xsshunterexpress_1  |       ^
xsshunterexpress_1  |
xsshunterexpress_1  | Error: EACCES: permission denied, open '/app/payload-fire-images/67fe8bc6-8b0c-445a-b9f5-672a952ecde1.png.gz'
xsshunterexpress_1  | Emitted 'error' event on WriteStream instance at:
xsshunterexpress_1  |     at errorOrDestroy (internal/streams/destroy.js:108:12)
xsshunterexpress_1  |     at WriteStream.onerror (_stream_readable.js:754:7)
xsshunterexpress_1  |     at WriteStream.emit (events.js:314:20)
xsshunterexpress_1  |     at internal/fs/streams.js:361:12
xsshunterexpress_1  |     at FSReqCallback.oncomplete (fs.js:156:23) {
xsshunterexpress_1  |   errno: -13,
xsshunterexpress_1  |   code: 'EACCES',
xsshunterexpress_1  |   syscall: 'open',
xsshunterexpress_1  |   path: '/app/payload-fire-images/67fe8bc6-8b0c-445a-b9f5-672a952ecde1.png.gz'
xsshunterexpress_1  | }
xsshunter-express_xsshunterexpress_1 exited with code 1
```

**Comment by trustinveritas** [comment]
Found solution... Had to change permission for folders inside the cloned github repo, because I'm running the docker rootles.
