### ISSUE TITLE
Cool idea, but... not working on vanilla Ubuntu

### ISSUE THREAD

**Issue by codearama** [mandatoryprogrammer/xsshunter-express#9]
```
$ docker-compose up -d postgresdb
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose f           ile version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key           , or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

OK, changed version to `version: "3.3"` ... that works I guess.

```
$ docker-compose up xsshunterexpress
Building xsshunterexpress
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 542, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 366, in ensure_image_exists
    self.build(cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1084, in build
    build_output = builder.build(
  File "/usr/lib/python3/dist-packages/docker/api/build.py", line 159, in build
    context = utils.tar(
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 30, in tar
    files=sorted(exclude_paths(root, exclude, dockerfile=dockerfile[0])),
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 49, in exclude_paths
    return set(pm.walk(root))
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 184, in rec_walk
    for f in os.listdir(current_dir):
PermissionError: [Errno 13] Permission denied: '/home/ropcc/xsshunter-express/postgres-db-data'
```

So, this was supposed to "just work" -- right? :')

Appreciate your help and supporting this project!

**Comment by anthonys1760** [comment]
If you run it again with `sudo` it should work.
